# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "Character" ("ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"NAME" VARCHAR NOT NULL);
create table "Sentence" ("ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"TEXT" VARCHAR NOT NULL,"CHARACTER_ID" BIGINT NOT NULL);
alter table "Sentence" add constraint "SUP_FK" foreign key("CHARACTER_ID") references "Character"("ID") on update NO ACTION on delete NO ACTION;

# --- !Downs

alter table "Sentence" drop constraint "SUP_FK";
drop table "Sentence";
drop table "Character";

