spring:
  # Prevent batch execution at startup
  batch.job.enabled: false
  profiles.active: development

---
spring:
  profiles: development

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:kaamelott
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create-drop

---
spring:
  profiles: production

  datasource:
    driverClassName: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate.ddl-auto: create
