create table "Character" ("CODE" VARCHAR NOT NULL PRIMARY KEY,"NAME" VARCHAR NOT NULL);
create table "Sentence" ("ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"TEXT" VARCHAR NOT NULL,"CHARACTER_CODE" VARCHAR NOT NULL);
alter table "Sentence" add constraint "FK_CHARACTER_CODE" foreign key("CHARACTER_CODE") references "Character"("CODE") on update NO ACTION on delete NO ACTION;
